//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TikettiDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kirjautuminen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kirjautuminen()
        {
            this.Asiakastiedot = new HashSet<Asiakastiedot>();
            this.IT_tukihenkilot = new HashSet<IT_tukihenkilot>();
        }
    
        public string Sahkoposti { get; set; }
        public string Salasana { get; set; }
        public int Taso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asiakastiedot> Asiakastiedot { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IT_tukihenkilot> IT_tukihenkilot { get; set; }
    }
}
