//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TikettiDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaitteenTyyppi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaitteenTyyppi()
        {
            this.Tikettitiedot = new HashSet<Tikettitiedot>();
        }
    
        public int LaitenumeroID { get; set; }
        public string Laitteen_nimi { get; set; }
        public int SijaintiID { get; set; }
    
        public virtual Sijainti Sijainti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tikettitiedot> Tikettitiedot { get; set; }
    }
}
