//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TikettiDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TikettiDBEntities : DbContext
    {
        public TikettiDBEntities()
            : base("name=TikettiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asiakastiedot> Asiakastiedot { get; set; }
        public virtual DbSet<IT_tukihenkilot> IT_tukihenkilot { get; set; }
        public virtual DbSet<Kirjautuminen> Kirjautuminen { get; set; }
        public virtual DbSet<LaitteenTyyppi> LaitteenTyyppi { get; set; }
        public virtual DbSet<Postinumero> Postinumero { get; set; }
        public virtual DbSet<Sijainti> Sijainti { get; set; }
        public virtual DbSet<Tikettitiedot> Tikettitiedot { get; set; }
        public virtual DbSet<YhteydenTyyppi> YhteydenTyyppi { get; set; }
    }
}
